# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='question',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
